export const radius = {
  none: 'var(--radius-none)',
  1: 'var(--radius-1)',
  2: 'var(--radius-2)',
  3: 'var(--radius-3)',
  4: 'var(--radius-4)',
  5: 'var(--radius-5)',
  6: 'var(--radius-6)',
  sm: 'var(--radius-sm)',
  10: 'var(--radius-10)',
  md: 'var(--radius-md)',
  14: 'var(--radius-14)',
  15: 'var(--radius-15)',
  lg: 'var(--radius-lg)',
  22: 'var(--radius-22)',
  xl: 'var(--radius-xl)',
  26: 'var(--radius-26)',
  35: 'var(--radius-35)',
  full: 'var(--radius-full)',
} as const;
