export const fontFamilies = {
  inter: 'var(--font-family-inter)',
  mono: 'var(--font-family-mono)',
} as const;

export const fontWeights = {
  light: 'var(--font-weight-light)',
  regular: 'var(--font-weight-regular)',
  medium: 'var(--font-weight-medium)',
  semibold: 'var(--font-weight-semibold)',
  bold: 'var(--font-weight-bold)',
} as const;

export const typography = {
  appPageTitle: {
    fontFamily: fontFamilies.inter,
    fontWeight: fontWeights.semibold,
    fontSize: 'var(--typography-app-page-title-font-size)',
    lineHeight: 'var(--typography-app-page-title-line-height)',
  },
  appSectionTitle: {
    fontFamily: fontFamilies.inter,
    fontWeight: fontWeights.semibold,
    fontSize: 'var(--typography-app-section-title-font-size)',
    lineHeight: 'var(--typography-app-section-title-line-height)',
  },
  appBody: {
    fontFamily: fontFamilies.inter,
    fontWeight: fontWeights.regular,
    fontSize: 'var(--typography-app-body-font-size)',
    lineHeight: 'var(--typography-app-body-line-height)',
  },
  appCaption: {
    fontFamily: fontFamilies.inter,
    fontWeight: fontWeights.regular,
    fontSize: 'var(--typography-app-caption-font-size)',
    lineHeight: 'var(--typography-app-caption-line-height)',
  },
  appMonoLabel: {
    fontFamily: fontFamilies.mono,
    fontWeight: fontWeights.medium,
    fontSize: 'var(--typography-app-mono-label-font-size)',
    lineHeight: 'var(--typography-app-mono-label-line-height)',
    letterSpacing: 'var(--typography-app-mono-label-letter-spacing)',
  },
  appMonoData: {
    fontFamily: fontFamilies.mono,
    fontWeight: fontWeights.regular,
    fontSize: 'var(--typography-app-mono-data-font-size)',
    lineHeight: 'var(--typography-app-mono-data-line-height)',
  },
  displayHero: {
    fontFamily: fontFamilies.inter,
    fontWeight: fontWeights.regular,
    fontSize: 'var(--typography-display-hero-font-size)',
    lineHeight: 'var(--typography-display-hero-line-height)',
    letterSpacing: 'var(--typography-display-hero-letter-spacing)',
  },
  headingH1: {
    fontFamily: fontFamilies.inter,
    fontWeight: fontWeights.regular,
    fontSize: 'var(--typography-heading-h1-font-size)',
    lineHeight: 'var(--typography-heading-h1-line-height)',
    letterSpacing: 'var(--typography-heading-h1-letter-spacing)',
  },
  headingH2: {
    fontFamily: fontFamilies.inter,
    fontWeight: fontWeights.regular,
    fontSize: 'var(--typography-heading-h2-font-size)',
    lineHeight: 'var(--typography-heading-h2-line-height)',
    letterSpacing: 'var(--typography-heading-h2-letter-spacing)',
  },
  headingH3: {
    fontFamily: fontFamilies.inter,
    fontWeight: fontWeights.regular,
    fontSize: 'var(--typography-heading-h3-font-size)',
    lineHeight: 'var(--typography-heading-h3-line-height)',
    letterSpacing: 'var(--typography-heading-h3-letter-spacing)',
  },
  headingH4: {
    fontFamily: fontFamilies.inter,
    fontWeight: fontWeights.regular,
    fontSize: 'var(--typography-heading-h4-font-size)',
    lineHeight: 'var(--typography-heading-h4-line-height)',
    letterSpacing: 'var(--typography-heading-h4-letter-spacing)',
  },
  bodyLg: {
    fontFamily: fontFamilies.inter,
    fontWeight: fontWeights.regular,
    fontSize: 'var(--typography-body-lg-font-size)',
    lineHeight: 'var(--typography-body-lg-line-height)',
    letterSpacing: 'var(--typography-body-lg-letter-spacing)',
  },
  bodyBase: {
    fontFamily: fontFamilies.inter,
    fontWeight: fontWeights.regular,
    fontSize: 'var(--typography-body-base-font-size)',
    lineHeight: 'var(--typography-body-base-line-height)',
    letterSpacing: 'var(--typography-body-base-letter-spacing)',
  },
  bodySm: {
    fontFamily: fontFamilies.inter,
    fontWeight: fontWeights.regular,
    fontSize: 'var(--typography-body-sm-font-size)',
    lineHeight: 'var(--typography-body-sm-line-height)',
    letterSpacing: 'var(--typography-body-sm-letter-spacing)',
  },
  labelUi: {
    fontFamily: fontFamilies.inter,
    fontWeight: fontWeights.regular,
    fontSize: 'var(--typography-label-ui-font-size)',
    lineHeight: 'var(--typography-label-ui-line-height)',
    letterSpacing: 'var(--typography-label-ui-letter-spacing)',
  },
  labelButton: {
    fontFamily: fontFamilies.inter,
    fontWeight: fontWeights.regular,
    fontSize: 'var(--typography-label-button-font-size)',
    lineHeight: 'var(--typography-label-button-line-height)',
    letterSpacing: 'var(--typography-label-button-letter-spacing)',
  },
  labelMonoKicker: {
    fontFamily: fontFamilies.mono,
    fontWeight: fontWeights.regular,
    fontSize: 'var(--typography-label-mono-kicker-font-size)',
    lineHeight: 'var(--typography-label-mono-kicker-line-height)',
    letterSpacing: 'var(--typography-label-mono-kicker-letter-spacing)',
  },
  wordmark: {
    fontFamily: fontFamilies.inter,
    fontWeight: fontWeights.regular,
    fontSize: 'var(--typography-wordmark-font-size)',
    lineHeight: 'var(--typography-wordmark-line-height)',
    letterSpacing: 'var(--typography-wordmark-letter-spacing)',
  },
} as const;
